name: Check and Duplicate Phaito.dmg and YML file

on:
    release:
        types: [published]

    schedule:
        - cron: '0 0 * * *'

    workflow_dispatch:

jobs:
    check-and-duplicate:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Get latest release
              id: get_release
              uses: octokit/request-action@v2.x
              with:
                  route: GET /repos/{owner}/{repo}/releases/latest
                  owner: Image-Salon
                  repo: phaito-electron-updates
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract data from release
              id: extract_data
              env:
                  DATA: ${{ steps.get_release.outputs.data }}
              run: |
                  printf '%s\n' "$DATA" > release_data.json
                  tag_name=$(jq -r '.tag_name' release_data.json)
                  version="${tag_name#v}"
                  echo "VERSION=$version" >> $GITHUB_ENV

                  release_id="$(jq -r '.id' release_data.json)"
                  echo "RELEASE_ID=$release_id" >> $GITHUB_ENV

                  assets_url="$(jq -r '.assets_url' release_data.json)"
                  echo "ASSETS_URL=$assets_url" >> $GITHUB_ENV

                  upload_url="$(jq -r '.upload_url' release_data.json | sed 's/{.*}//')"
                  echo "UPLOAD_URL=$upload_url" >> $GITHUB_ENV

            - name: Get version
              env:
                  VERSION: ${{ env.VERSION }}
                  RELEASE_ID: ${{ env.RELEASE_ID }}
                  ASSETS_URL: ${{ env.ASSETS_URL }}
                  UPLOAD_URL: ${{ env.UPLOAD_URL }}
              run: |
                  echo "VERSION: $VERSION"
                  echo "RELEASE_ID: $RELEASE_ID"
                  echo "ASSETS_URL: $ASSETS_URL"
                  echo "UPLOAD_URL: $UPLOAD_URL"

            - name: Check and duplicate Phaito.dmg
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  ASSETS_URL: ${{ env.ASSETS_URL }}
                  UPLOAD_URL: ${{ env.UPLOAD_URL }}
              run: |
                  assets=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "$ASSETS_URL")

                  if ! echo "$assets" | jq -e '.[] | select(.name == "Phaito.dmg")'; then
                    file_to_duplicate=$(echo "$assets" | jq -r '.[] | select(.name | test("^Phaito_.*\\.dmg$")) | .browser_download_url')
                    if [ -n "$file_to_duplicate" ]; then
                      # Download the file
                      curl -L -o Phaito.dmg "$file_to_duplicate"
                      
                      # Upload the file
                      curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
                          -H "Content-Type: application/octet-stream" \
                          --data-binary @"Phaito.dmg" \
                          "$UPLOAD_URL?name=Phaito.dmg&label=Phaito.dmg"
                    fi
                  fi

            - name: Generate latest-mac.yml if not exists
              if: success()
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  ASSETS_URL: $(cat assets_url.txt)
                  VERSION: ${{ env.VERSION }}
              run: |
                  assets=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "$ASSETS_URL")

                  if ! echo "$assets" | jq -e '.[] | select(.name == "latest-mac.yml")'; then

                    file_to_duplicate_dmg=$(echo "$assets" | jq -r '.[] | select(.name | test("^Phaito_.*\\.dmg$")) | .browser_download_url')
                    if [ -n "$file_to_duplicate_dmg" ]; then
                      # Download the file
                      curl -L -o "Phaito_${VERSION}.dmg" "$file_to_duplicate_dmg"
                    fi

                    file_to_duplicate_zip=$(echo "$assets" | jq -r '.[] | select(.name | test("^Phaito_.*\\.zip$")) | .browser_download_url')
                    if [ -n "$file_to_duplicate_zip" ]; then
                      # Download the file
                      curl -L -o "Phaito_${VERSION}.zip" "$file_to_duplicate_zip"
                    fi

                    node scripts/generate-latest-mac-yml.js "${VERSION}"
                  fi

            - name: Upload latest-mac.yml
              if: success()
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  UPLOAD_URL: $(cat upload_url.txt | sed 's/{.*}//')
              run: |
                  if [ -f "latest-mac.yml" ]; then
                    curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
                        -H "Content-Type: text/yaml" \
                        --data-binary @"latest-mac.yml" \
                        "$UPLOAD_URL?name=latest-mac.yml&label=latest-mac.yml"
                  fi
